on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Clone
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: List stuff
        run: ls -al

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: heppe/salesapp-postgres
          context: database
          file: database/Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build and push
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          push: true
          context: backend
          tags: heppe/salesapp-backend

      - name: Build and push
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          push: true
          context: frontend
          tags: heppe/salesapp-frontend

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}